### ISSUE TITLE
Change server names in examples

### ISSUE THREAD

**Issue by jimsch** [ace-wg/ace-oauth#123]
I think that it would make things easier to read if we named the different servers so that it is clear what the function of the server is based solely on it's name w/o having to understand the content of the message.

Thus names like "authorize.example.com" and "resource.example.com" would make it easier to parse examples on a stand alone basis.

**Comment by LudwigSeitz** [comment]
I checked the examples and found two instances of "server.example.com" which I changed to "as.example.com".

Is "as.example.com" and "rs.example.com" clear enough or would you prefer to have them written out
in some way?

**Comment by jimsch** [comment]
That would be just fine - just something that is not server is all I was asking for

**Comment by LudwigSeitz** [comment]
Then that is already fixed.
