### ISSUE TITLE
Define an RS->AS field to allow in initial requests

### ISSUE THREAD

**Issue by jimsch** [ace-wg/ace-oauth#124]
In section 5.1.2 I want to define a field that would be copied intact from the response of the RS to the request from the C to the AS.  This would allow the RS to specify things like what it believes the aud or scope should be on the token returned.

**Comment by LudwigSeitz** [comment]
This is unauthenticated and possibly unprotected communication. Should the RS really reveal that much information to an unknown client?

**Comment by jimsch** [comment]
It could be an encrypted field rather than a plain text field.  However it would allow for a better set of things like scopes to be set w/o the client needing to understand how that information is created.

**Comment by LudwigSeitz** [comment]
This kind of things is defined in UMA. Better solved in a profile, not a core functionality.
