### ISSUE TITLE
Value Type of parameter 'profile'?

### ISSUE THREAD

**Issue by obgm** [ace-wg/ace-oauth#126]
(Section numbers refer to version -08)

I wonder what is expected as value of the parameter `profile` in the AS-to-Client response. Figure 12 in section 5.6.5 states that the value type of the `profile` parameter is a CBOR text string.  The registration template in section 8.6.1, on the other hand, allows registering a numeric identifier for a profile ("Profile ID").

So, if a registered profile `foo_over_bar` has the numeric ID 42, this would leave two possible values for the parameter profile:

```
  6C                          # text(12)
    666F6F5F6F7665725F626172 # "foo_over_bar"
```

or

```
   62      # text(2)
      3432 # "42"
```

For more compact signaling, I suggest allowing `profile` to be of a numeric type such that:

```
  18 2A # unsigned(42)
```

**Comment by LudwigSeitz** [comment]
Sounds reasonable. We need to look over all these "inheritances" from ASCII-OAuth and check whether we rather want to have them as numeric types.

**Comment by LudwigSeitz** [comment]
I would even go so far to REQUIRE the numeric abbreviation.
