### ISSUE TITLE
Register scope with JWT

### ISSUE THREAD

**Issue by erdtman** [ace-wg/ace-oauth#127]
a new claim is defined, scope.
We add it to the CWT mapping register but not to the JWT registry of claims.

New IANA section is needed and maybe some explaining text.

**Comment by erdtman** [comment]
check if already done https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-09#section-5.4.1

**Comment by LudwigSeitz** [comment]
I am aware of the "scp" claim from the token-exchange draft, and I hate its guts!
Scope is already a space-delimited list of [scope-tokens](https://tools.ietf.org/html/rfc6749#section-3.3) but they choose to make "scp" an array of scopes, so basically it's a doubly-nested array. Processing these in code is not fun, much less so on constrained devices.
