### ISSUE TITLE
Local Token Validation example: public key missing

### ISSUE THREAD

**Issue by chrysn** [ace-wg/ace-oauth#144]
When reading the draft as someone generally not familiar with ACE, those two lines seem to be in conflict:

> The request *contains the public key of the client* and the Audience parameter set to "tempSensorInLivingRoom", a value that the temperature sensor identifies itself with.

>     Request-Payload :
>     {
>       "grant_type" : "client_credentials",
>       "aud" : "tempSensorInLivingRoom",
>       "client_id" : "myclient",
>       "client_secret" : "qwerty"
>     }

(none of those lines look like a public key to me).

Is something missing in the example, or did I just miss important context? The line "first generates a public-private key pair used for communication security with the RS" seems to imply that the key pair just generated (part of which should be contained in the request to AS) is not already used to contact the AS.

**Comment by LudwigSeitz** [comment]
Good catch. Figure 18 is missing the "cnf" parameter in the Request-Payload.
