### ISSUE TITLE
Example E.2: token reuse, odd audience

### ISSUE THREAD

**Issue by chrysn** [ace-wg/ace-oauth#145]
In the example "Introspection Aided Token Validation", the access token dealt to the key fob is the same b64'SlAV32hkKG ...' that we saw in the previous example as encoding for a semantic token; I think it would ease readability if that actually said something more Op4Que123-ish.

In the same example, the audience of the original token is described in the text to be broad (PACS1337), while the audience in the message A payload is already narrowed down to "lockOfDoor4711", which AFAICT should only happen during the introspection phase.

And (and this is where I start to lean out over what I'm relatively confident to have understood), shouldn't the AS's response contain the kid=c29t... / k=ZoRSOrFz... information shared with the fob earlier? For where would otherwise be the pre-shared key between C and RS come from during the setup of F?

**Comment by LudwigSeitz** [comment]
The access token being the same as in the previous example is just laziness of the me. I'll fix that (but what is Op4Que123? ;-) ).
Your second point: Indeed it makes more sense without the aud parameter in message A. I'll fix that as well.
Your last point: Good catch again, probably some copy-past crud that stuck and never got noticed.
