### ISSUE TITLE
What is the correct content type for a 4.01 response

### ISSUE THREAD

**Issue by jimsch** [ace-wg/ace-oauth#146]
I have been using application/cbor, but the document says application/ace+cbor.   

If that is to be used then it needs to be created as a new content type.

**Comment by LudwigSeitz** [comment]
That was copied here from Olaf's draft. I'll ask him what he intended, but I think application/cbor should be fine.

**Comment by jimsch** [comment]
I have started to lean towards thinking that we need to defined the new content type.  There was some discussion in the last CoRE virtual meeting where where somebody was returning data as part of a 4.01 response which was not this information and therefore trying to decide if this is what the extra information is might need to be more explicit.
