### ISSUE TITLE
Robert Wilton Comment on the introduction and the relationship to profiles

### ISSUE THREAD

**Issue by hannestschofenig** [ace-wg/ace-oauth#182]
Robert wrote: 

> One minor comment:  I found it a slight leap in the introduction in the final paragraph ("More detailed, ...") that talks about interoperable specifications (implying that specification is not interoperable) and profiles (where it isn't clear where these have come from).  So, an extra sentence to bridge the concepts might be helpful in the introduction.  As a nit, the paragraph is also missing a comma in "interoperate while".

**Comment by hannestschofenig** [comment]
Addressed by this PR:
https://github.com/ace-wg/ace-oauth/pull/181

**Comment by LudwigSeitz** [comment]
Merged
