### ISSUE TITLE
 Erik Kline Review Comments

### ISSUE THREAD

**Issue by hannestschofenig** [ace-wg/ace-oauth#188]
> [[ comments ]]
> 
> [ section 5.10.3 ]
> 
> * It seems to me that making the described expired token list behaviour
>   a MUST may be overspecifying things.  Is there some reason it can't be
>   downgraded to SHOULD?
> 
>   Also: does this described algorithm rely upon all exi values being
>   essentially the same?  I was thinking about expires_in values varying
>   wildly (for whatever reason) and I wasn't sure how this sequence number
>   tracking would work in that case.
> 

I am not sure about this comment. I will create a separate issue. 

> [ section 6.6 ]
> 
> * I presume another alternative is for the RS to delay (or postpone with
>   some error code?) request handling until time synchronization (NTP, NITZ,
>   ...) has completed (even if only the time is sync'd/stepped and no other
>   parameters are coordinated).
> 
> 

Nits addressed. 

> [[ nits ]]
> 
> [ section 5.8.1 ]
> 
> * "in order allow" -> "in order to allow"
> 
> * ", specifically" > probably two separate sentences reads more clearly.
>   ". Specifically"
> 
> * "}W" -> "}"?
> 
> * "can only use to" -> "can only be used to"?
> 
> [ section 6.6 ]
> 
> * "loose" -> "lose"

**Comment by hannestschofenig** [comment]
Partially addressed by PR https://github.com/ace-wg/ace-oauth/pull/189

**Comment by LudwigSeitz** [comment]
Merged
