### ISSUE TITLE
Review by Lars Eggert 

### ISSUE THREAD

**Issue by hannestschofenig** [ace-wg/ace-oauth#191]
> "Table of Contents", paragraph 1, nit:
> > Table of Contents
> 
> Some sections don't use title case.
> 
> Section 4, paragraph 9, nit:
> -    In Bluetooth Low Energy, for example, advertisements are broadcasted
> -                                                                      --
> +    In Bluetooth Low Energy, for example, advertisements are broadcast

Changed. 

> Section 5.3, paragraph 15, nit:
> -    freshness nevetheless, the RS has included a "cnonce" parameter (see
> +    freshness nevertheless, the RS has included a "cnonce" parameter (see
> +                  +
> 
Changed. 

> "Appendix E.", paragraph 33, nit:
> -       as playload the Access Information, including the access token and
> -           -
> +       as payload the Access Information, including the access token and

Changed.

**Comment by LudwigSeitz** [comment]
Fixed.
